[package]
name = "nanbox"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"
description = "Another NaN boxer"

[dependencies]
dumpster = { version = "1.1.0", optional = true }
spin = "0.10.0"

[features]
dumpster = ["dep:dumpster"]
